title: Farzam Nazari
logo: https://github.com/Farzam1372/Farzam1372.github.io/blob/18b99c74ff339b462fb965ef9bcc311ac873cb6c/headshot.jpeg
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
