title: Farzam Nazari
logo: https://github.com/Farzam1372/Farzam1372.github.io/blob/5e7caa7286fb513d6b2b757a81576947390a3c3e/headshot.jpeg
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
