title: Farzam Nazari
logo: ![Profile Picture](https://github.com/Farzam1372/Farzam1372.github.io/raw/main/headshot.jpeg){: .circular-logo}
#description: Text below image
show_downloads: true
theme: jekyll-theme-minimal
