title: Farzam Nazari
logo: ![Profile Picture](https://raw.githubusercontent.com/Farzam1372/Farzam1372.github.io/main/headshot.jpeg)
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
